### ISSUE TITLE
UploadImg 组件小程序中U并没有URL.createObjectURL

### ISSUE THREAD

**Issue by comlejade** [cqkqinfo/ui#10]
小程序这里该怎么处理
![image](https://user-images.githubusercontent.com/15702577/149776805-635dca92-0aaa-4591-99f0-ef220c5838a2.png)

**Comment by mushan0x0** [comment]
这个只是示例，真实项目要用upload方法方法把file上传到服务器，然后返回一个链接给组件

**Comment by comlejade** [comment]
这样有问题吗？

![image](https://user-images.githubusercontent.com/15702577/149853178-2aeb682e-d088-4fc3-bf35-a45157686960.png)

**Comment by mushan0x0** [comment]
> 这样有问题吗？
> 
> ![image](https://user-images.githubusercontent.com/15702577/149853178-2aeb682e-d088-4fc3-bf35-a45157686960.png)

uploadFile成功后好像是一个json字符串，要解析一下吧，用法是这样的没错

**Comment by comlejade** [comment]
这是啥，上传成功后报错
![image](https://user-images.githubusercontent.com/15702577/149855261-6466a984-ae93-44a6-8315-317c078234e7.png)

**Comment by mushan0x0** [comment]
> 这是啥，上传成功后报错 ![image](https://user-images.githubusercontent.com/15702577/149855261-6466a984-ae93-44a6-8315-317c078234e7.png)

这个是组件卸载后执行了setState，不影响，但我们后面会注意修复这种报错
