### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by comlejade** [cqkqinfo/ui#12]
前面1.8的版本的时候 github actions 就报错
![image](https://user-images.githubusercontent.com/15702577/152717994-6c4ede53-be87-4337-9d3f-d707ae230dcb.png)

更新到最的版本，本地安装也报错

![image](https://user-images.githubusercontent.com/15702577/152717928-96ac80d5-2dc6-4f6f-8841-667cbd6ea823.png)

**Comment by mushan0x0** [comment]
在项目根目录添加.npmrc文件

往里面添加sentrycli_cdnurl=https://cdn.npm.taobao.org/dist/sentry-cli 试试呢

**Comment by comlejade** [comment]
> 在项目根目录添加.npmrc文件
> 
> 往里面添加sentrycli_cdnurl=https://cdn.npm.taobao.org/dist/sentry-cli 试试呢

又来了新的

![image](https://user-images.githubusercontent.com/15702577/152722238-ee4f28c6-33a7-41b0-a75a-24a8d066f876.png)

**Comment by mushan0x0** [comment]
在yarn.lock 找到filelist这个删除再试试

**Comment by comlejade** [comment]
我把 node_modules 和 lock 文件都删了，sentrycli_cdnurl也加了，又重新回到了这个错误

![image](https://user-images.githubusercontent.com/15702577/152728239-3ec979e0-79f0-4e33-ae87-8544cc305c7d.png)

**Comment by comlejade** [comment]
很奇怪，npm 可以安装，yarn 不行

**Comment by mushan0x0** [comment]
lock文件不用删，删了会装得很慢，把里面的这个删了就行了
![image](https://user-images.githubusercontent.com/29084441/152730110-f29dba94-6ef6-4ebf-a630-abba7df33368.png)

**Comment by comlejade** [comment]
换成 npm 安装就好了，yarn 一直安装失败

**Comment by mushan0x0** [comment]
那试一下配.yarnrc吧，默认yarn会读取.npmrc的，你的似乎没生效
![image](https://user-images.githubusercontent.com/29084441/152743536-4d8257bd-33b5-4229-a342-0a42c9c1a2a4.png)

**Comment by comlejade** [comment]
我一开始用的就是 .yarnrc，用 yarn config list 查看，发现设置成功了，但安装还是失败；就换了 npm，这才成功的；搞了一上午，不想再浪费时间了，先凑合着用吧

**Comment by mushan0x0** [comment]
那这个issue先关了
