### ISSUE TITLE
List如果每项的高度都不同且不能确定高度，该怎么启用虚拟滚动

### ISSUE THREAD

**Issue by comlejade** [cqkqinfo/ui#13]
像这种右侧列表，由于数据太多，且高度不确定，切换的时候很卡，想要使用虚拟长列表，但是看到好多都是要固定高度，这种如何处理

<img width="375" alt="image" src="https://user-images.githubusercontent.com/15702577/153702562-0dbc3ce2-c880-434e-822e-6fb73501f335.png">

**Comment by mushan0x0** [comment]
这种情况可以用 native组件 https://cqkqinfo.github.io/ui/components/general/native ，可以绕开react diff 过程直接设置组件状态，remax的虚拟滚动不靠谱，效果不好，可以用这个来做
