### ISSUE TITLE
 error at token "*"

### ISSUE THREAD

**Issue by lixinxiaobai** [cqkqinfo/ui#14]
error at token "*"
  1671 | }
  1672 | 
> 1673 | .adm-dialog-main > * {
       |                   ^
  1674 |   flex: none;
  1675 | }
  1676 |

**Comment by mushan0x0** [comment]
使用的什么组件报错的，试一下配置按需加载呢 https://cqkqinfo.github.io/ui/#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD
