### ISSUE TITLE
FormItem设置disabled貌似不生效，直接设置在Picker上貌似也不生效

### ISSUE THREAD

**Issue by furan495** [cqkqinfo/ui#16]

**Comment by mushan0x0** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/29084441/156723518-45c851e3-8466-4c4f-9ac3-04a6628f3197.png">
加到picker上，我这里是生效的呢，你是什么平台的

**Comment by furan495** [comment]
我是小程序里面，开始是设置在了FormItem上，看了下文档FormItem貌似没有disabled属性，但是readOnly会隐藏placeholder；
后来改成了FormItem包裹ReInput，在ReInput上设置disabled就可以了；
![image](https://user-images.githubusercontent.com/87800349/156730929-1e6dc76c-3b15-49be-9f9c-91e82389b418.png)

**Comment by mushan0x0** [comment]
好的那我关了
