### ISSUE TITLE
FomItem组件中文模式下：在小程序环境中输入内容会和placeholder重叠

### ISSUE THREAD

**Issue by furan495** [cqkqinfo/ui#17]

**Comment by mushan0x0** [comment]
输入中会重叠，完成后就没有，因为小程序onInput只要输入完成后onInput才会触发

**Comment by furan495** [comment]
刚又看了下，在支付宝里没有这种情况，微信里会有这种情况;
![image](https://user-images.githubusercontent.com/87800349/156998767-16210f20-c30b-4221-b7c9-2f89783996e0.png)
支付宝里就是input的placeholder属性
<img width="428" alt="image" src="https://user-images.githubusercontent.com/87800349/156998946-201b69a4-403b-439c-97bc-1bf0c7327f71.png">
微信里是个单独的view
有点头大

**Comment by mushan0x0** [comment]
因为placeholder是自己实现的，现在已经修复了，处理为光标选中时就隐藏placeholder

**Comment by furan495** [comment]
确实可以了，大佬🐮🍺；ORZ
