### ISSUE TITLE
微信小程序中，form.setFieldsValues清空表单会触发表单验证

### ISSUE THREAD

**Issue by furan495** [cqkqinfo/ui#18]
![image](https://user-images.githubusercontent.com/87800349/157185737-52c2c672-4890-410f-9770-7abc44eba9de.png)
如下图:支付宝中没有发现这个问题
<img width="381" alt="image" src="https://user-images.githubusercontent.com/87800349/157185788-f505f1cf-5c0d-4327-9c05-35d422caae49.png">

**Comment by mushan0x0** [comment]
清空表单的话试试form.resetFields呢，cardType:1设置到formItem的initialValue属性上。表单应该每个平台表现是一致的吧。

**Comment by furan495** [comment]
我这边比较特殊，是要清除部分表单项，form.resetFields会清空所有的表单项，不大符合业务场景。

**Comment by mushan0x0** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/29084441/157186884-56afe63a-d77e-46d3-8566-44bbd570eba5.png">
清空部分值的话试试这个呢

**Comment by furan495** [comment]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/87800349/157188149-68919463-df84-42c6-b3e6-6ef820ad0e39.png">
微信里清掉了一部分
![image](https://user-images.githubusercontent.com/87800349/157188492-42cf0255-4d2c-4de8-b3f3-f0628e8778a3.png)

**Comment by mushan0x0** [comment]
阿里小程序清不掉吗

**Comment by furan495** [comment]
阿里的没问题，微信不行

**Comment by furan495** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/87800349/157189673-53ebe6b0-8183-4375-be01-d4c40fd12545.png">
微信控制台有这些警告，不能设置空值么。

**Comment by mushan0x0** [comment]
应该是bug，等会我看看

**Comment by mushan0x0** [comment]
> 阿里的没问题，微信不行

我没有复现出来，可以提供一点代码不

**Comment by furan495** [comment]
怎样提供呢，可以直接把源码粘进来么。

**Comment by mushan0x0** [comment]
表单使用的地方部分截图或者粘贴进来就行了

**Comment by furan495** [comment]
`import React from 'react'
import { View } from 'remax/one'
import { Form, Picker, Radio, Button, ReInput, FormItem, } from '@kqinfo/ui'

export default () => {

  const [form] = Form.useForm()

  const cardTypes = [
    { label: '居民身份证', value: 1 },
    { label: '护照或者其他有效证件', value: 6 }
  ]

  const toSaveOrder = async () => {
    form.submit()
    await form.validateFields()
    form.setFieldsValue({ sex: '', name: '', cardNo: '', mobile: '', cardType: 1 })
  }

  return (
    <View >
      <Form cell form={form} values={{ cardType: 1 }} requiredMark={false}>
        <FormItem label='姓名' name='name' rules={[{ required: true, message: '请输入姓名' }]} >
          <ReInput placeholder='姓名' />
        </FormItem>
        <FormItem label='性别' name='sex' rules={[{ required: true, message: '请选择性别' }]}>
          <Radio.Group  >
            <Radio value={1}>男</Radio>
            <Radio value={2}>女</Radio>
          </Radio.Group>
        </FormItem>
        <FormItem label='证件类型' name='cardType' >
          <Picker data={cardTypes} />
        </FormItem>
        <FormItem name='cardNo' label='证件号码' rules={[{ required: true, message: '请输入正确的证件号码' }]} >
          <ReInput placeholder='身份证号或者其他有效证件' />
        </FormItem>
        <FormItem label='手机号码' name='mobile' rules={[{ required: true, message: '请输入正确的手机号码' }]} >
          <ReInput placeholder='手机号码' />
        </FormItem>
      </Form>

      <Button block size='small' type='attract' onTap={toSaveOrder}>保存</Button>
    </View>
  )
}
`
去除业务逻辑后最小化的代码，在支付宝里是可以的，在微信中不行。

**Comment by mushan0x0** [comment]
@furan495 感谢反馈，已经修复了
