### ISSUE TITLE
Picker控件 datatime模式的bug

### ISSUE THREAD

**Issue by tiancaidaren** [cqkqinfo/ui#19]
<Picker className={clsx(props.className, styles.root)}
                mode={"datetime"}
                onChange={(e) => {
                    console.log(e);
                }}>
            <View className={styles.input_layout}>
                <Input className={styles.input} disabled onInput={console.log} placeholder={props.placeholder}
                       value={"dfsfdsfds"}/>
            </View>
        </Picker>
![image](https://user-images.githubusercontent.com/55011932/157642350-d9c3a2ab-97f5-4769-956e-a00d12744a42.png)

有些情况会报错  如上图，对undefined判断不够严谨

**Comment by mushan0x0** [comment]
修复了
