### ISSUE TITLE
formItem触发表单验证后after属性设置的内容会消失

### ISSUE THREAD

**Issue by furan495** [cqkqinfo/ui#22]
![image](https://user-images.githubusercontent.com/87800349/162658648-210a7fa1-89cd-441b-b198-41ba74042abd.png)
如图:
![image](https://user-images.githubusercontent.com/87800349/162658700-4d1dbbb0-9531-4768-b2f1-4132be65b896.png)
触发验证后after节点消失了

**Comment by mushan0x0** [comment]
感谢反馈，已修复 a654d257b38c672cea854de8b61902b73d957a77
