### ISSUE TITLE
Search的focus不生效

### ISSUE THREAD

**Issue by WanAn0902** [cqkqinfo/ui#29]
设置focus=true，页面进入没有自动获取焦点`<Search focus={true}  />`

**Comment by WanAn0902** [comment]
> 

<Search focus={true}  />

**Comment by mushan0x0** [comment]
@WanAn0902 已修复

**Comment by WanAn0902** [comment]
> @WanAn0902 已修复

没有啊，我拉了最新包，设置focus后，虽然会默认不展示placeholder了，但是光标并没有在输入框内，也无法直接输入内容呢

**Comment by mushan0x0** [comment]
> 

你是web端吗，web端好像有限制

**Comment by WanAn0902** [comment]
> @WanAn0902 你是web端吗，web端好像有限制

小程序呢，在开发工具里

**Comment by mushan0x0** [comment]
> > @WanAn0902 你是web端吗，web端好像有限制
> 
> 小程序呢，在开发工具里

1.13.17修复的，你是什么版本
