### ISSUE TITLE
微信，只使用List组件会重复请求，加上Search组件只请求一次

### ISSUE THREAD

**Issue by zl2589** [cqkqinfo/ui#30]
只使用List组件时，getList方法用useCallback包裹后，仍会重复请求。
若加上Search组件，则只请求一次

**Comment by mushan0x0** [comment]
> 只使用List组件时，getList方法用useCallback包裹后，仍会重复请求。 若加上Search组件，则只请求一次

截图一下代码看看呢

**Comment by zl2589** [comment]
![image](https://user-images.githubusercontent.com/43987475/175844182-1c026be9-48b9-4ec8-96e2-609f1d8c7932.png)

**Comment by mushan0x0** [comment]
> ![image](https://user-images.githubusercontent.com/43987475/175844182-1c026be9-48b9-4ec8-96e2-609f1d8c7932.png)

listData那个部分代码看看

**Comment by zl2589** [comment]
![image](https://user-images.githubusercontent.com/43987475/175846241-dfcd0dfc-9f7c-4cec-b96f-0540b35ed905.png)

**Comment by mushan0x0** [comment]
> ![image](https://user-images.githubusercontent.com/43987475/175846241-dfcd0dfc-9f7c-4cec-b96f-0540b35ed905.png)

看一下接口的返回值和请求参数呢

**Comment by mushan0x0** [comment]
> > ![image](https://user-images.githubusercontent.com/43987475/175846241-dfcd0dfc-9f7c-4cec-b96f-0540b35ed905.png)
> 
> 看一下接口的返回值和请求参数呢

浏览器的network面板截图

**Comment by zl2589** [comment]
![image](https://user-images.githubusercontent.com/43987475/175846740-e4e445bc-1511-4cb9-bfc3-9f935ce0889f.png)
![image](https://user-images.githubusercontent.com/43987475/175846802-f63bcf84-d7dd-4bb8-b562-68fde9b0f2e4.png)
![image](https://user-images.githubusercontent.com/43987475/175846838-9e52545d-a7ed-48db-9fc8-51ea84bcb099.png)

另外：我刚刚发现与Search无关，是编译之后第一次进入都会请求两次，返回上一页再进入只请求一次

**Comment by mushan0x0** [comment]
> ![image](https://user-images.githubusercontent.com/43987475/175846740-e4e445bc-1511-4cb9-bfc3-9f935ce0889f.png) ![image](https://user-images.githubusercontent.com/43987475/175846802-f63bcf84-d7dd-4bb8-b562-68fde9b0f2e4.png) ![image](https://user-images.githubusercontent.com/43987475/175846838-9e52545d-a7ed-48db-9fc8-51ea84bcb099.png)
> 
> 另外：我刚刚发现与Search无关，是编译之后第一次进入都会请求两次，返回上一页再进入只请求一次

应该是父级状态更新导致list重新挂载导致的，如果你用的kqinfo/ui里的axios做得请求的话我可以在axios上做一个防止重复请求的功能

**Comment by zl2589** [comment]
好的 了解了 谢谢你
