### ISSUE TITLE
怎么覆盖样式呢

### ISSUE THREAD

**Issue by fhyoga** [cqkqinfo/ui#33]
remax: 2.9.1

less的:global语法覆盖不了组件库的样式
我想覆盖红框里元素的css
<img width="822" alt="image" src="https://user-images.githubusercontent.com/20250430/178246564-089f74f5-22c6-4b0d-a3e7-0ead746f5106.png">

这样写不生效
![image](https://user-images.githubusercontent.com/20250430/178246701-5cb1502b-31d4-4161-b991-a2a2147eac85.png)

**Comment by mushan0x0** [comment]
每个组件分了很多自定义类名，<Card className={style.card}/>，如果类名没暴露出来的话可以提issues

**Comment by fhyoga** [comment]
2.14+的源码不开源了吗？没找到，想参考下实现

**Comment by mushan0x0** [comment]
> 

更新了
