### ISSUE TITLE
List组件下拉

### ISSUE THREAD

**Issue by fhyoga** [cqkqinfo/ui#35]
考虑加个下拉刷新的feature，或者暴露一个下拉事件吗。感觉是个比较常见的场景

**Comment by fhyoga** [comment]
https://www.npmjs.com/package/parsec-hooks 这个lib的源码是开放的吗，list组件的逻辑略复杂，需要参考下

**Comment by mushan0x0** [comment]
小程序吗，直接用页面的下拉事件可以做
