### ISSUE TITLE
表单样式错乱

### ISSUE THREAD

**Issue by comlejade** [cqkqinfo/ui#4]
![image](https://user-images.githubusercontent.com/15702577/148721125-3d22675c-38c1-4a74-8b45-212c4c309b5b.png)
![image](https://user-images.githubusercontent.com/15702577/148721139-c08ac9f6-887d-4d98-9e42-4b9ca45a3aca.png)
![image](https://user-images.githubusercontent.com/15702577/148721233-7f8d7422-4ce1-4534-8555-b0a8bd384fbf.png)

安装的是最新版本

**Comment by mushan0x0** [comment]
城市数据是什么样的 @comlejade

**Comment by comlejade** [comment]
> 城市数据是什么样的 @comlejade

我就是用你们获取城市数据的接口，只不过把json数据下下来保存在了本地

**Comment by mushan0x0** [comment]
> > 城市数据是什么样的 @comlejade
> 
> 我就是用你们获取城市数据的接口，只不过把json数据下下来保存在了本地

把省市区formitem去掉后正常不

**Comment by comlejade** [comment]
> > > 城市数据是什么样的 @comlejade
> > 
> > 
> > 我就是用你们获取城市数据的接口，只不过把json数据下下来保存在了本地
> 
> 把省市区formitem去掉后正常不

去掉就正常了

**Comment by mushan0x0** [comment]
![image](https://user-images.githubusercontent.com/29084441/148723608-0dcd43e7-ec53-46a3-adb5-a301035c4fb0.png)

建议用这个方法获取城市数据，放在本地会增加打包体积

**Comment by comlejade** [comment]
> ![image](https://user-images.githubusercontent.com/29084441/148723608-0dcd43e7-ec53-46a3-adb5-a301035c4fb0.png)
> 
> 建议用这个方法获取城市数据，放在本地会增加打包体积

这跟样式有什么关系呢？还有 mini-css-extract-plugin 一直报冲突

**Comment by mushan0x0** [comment]
这个是transfer-change 组件的city模式解析失败了，city模式只能解析在线的城市数据，导致解析出来全是- - - - -这样的数据，跟样式没关系

这个报错是插件的问题，但是不影响项目运行，可以在`remax.config.js`里添加下面代码来去掉警告

```js
 config.devServer.quiet(true);
```

**Comment by comlejade** [comment]
> 

这样啊，我试试

**Comment by comlejade** [comment]
![image](https://user-images.githubusercontent.com/15702577/148736802-b6767d02-e8f2-4270-94d0-e2e1bf86f9c4.png)

这回可真有点莫名其妙了，同样是 TransferChange 注销掉就正常了

**Comment by mushan0x0** [comment]
你看一下addressOptions有没有获取到呢，没有的话看一下是不是没有加合法域，具体的看一下这个 https://cqkqinfo.github.io/ui/utils/business/get-address-options

**Comment by comlejade** [comment]
> 你看一下addressOptions有没有获取到呢，没有的话看一下是不是没有加合法域，具体的看一下这个 https://cqkqinfo.github.io/ui/utils/business/get-address-options

我这开启了不校验合法域名

**Comment by mushan0x0** [comment]
> > 你看一下addressOptions有没有获取到呢，没有的话看一下是不是没有加合法域，具体的看一下这个 https://cqkqinfo.github.io/ui/utils/business/get-address-options
> 
> 我这开启了不校验合法域名

那我看一下

**Comment by comlejade** [comment]
> > > 你看一下addressOptions有没有获取到呢，没有的话看一下是不是没有加合法域，具体的看一下这个 https://cqkqinfo.github.io/ui/utils/business/get-address-options
> > 
> > 
> > 我这开启了不校验合法域名
> 
> 那我看一下

![image](https://user-images.githubusercontent.com/15702577/148737810-3b012abb-9d40-4eb5-be8c-575ad85a5366.png)

**Comment by mushan0x0** [comment]
我这样并没有复现呢，可以粘一下代码吗
```tsx
import React, { useState, useEffect } from 'react';
import {
  Space,
  Picker,
  PartTitle,
  FormItem,
  Icon,
  TransferChange,
  Form,
  getAddressOptions,
} from '@kqinfo/ui';

export default () => {
  const [form] = Form.useForm();
  const [addressOptions, setAddressOptions] = useState<any[]>([]);
  useEffect(() => {
    getAddressOptions().then(options => setAddressOptions(options));
  }, []);
  return (
    <Space vertical size={'10px'}>
      <PartTitle>基本使用</PartTitle>
      <Form form={form} cell onFinish={console.log} labelWidth={'4em'} shadowProps={{shadowColor: false}}>
        <FormItem
          label={'城市'}
          rules={[{ required: true }]}
          name={'city'}
          after={<Icon name={'kq-right'} color={'#666'} />}
        >
          <TransferChange mode={'city'} onChange={console.log}>
            <Picker cols={3} data={addressOptions}>
              请选择
            </Picker>
          </TransferChange>
        </FormItem>
      </Form>
    </Space>
  );
};
```

**Comment by comlejade** [comment]
import React, { useState, useEffect } from 'react';
import { View } from 'remax/wechat';
import {
  Form,
  FormItem,
  ReInput,
  TransferChange,
  Space,
  Button,
  Picker,
  getAddressOptions,
  Icon,
  ReTextarea
} from '@kqinfo/ui';

const AddrAdd: React.FC = () => {
  const [form] = Form.useForm();
  const [addressOptions, setAddressOptions] = useState<any[]>([]);

  useEffect(() => {
    getAddressOptions().then(options => setAddressOptions(options));
  }, [])

  return (
    <View>
      <Form form={form} cell shadowProps={{ shadowColor: false }}>
        <FormItem label={'收货人'} name={'concat'} rules={[{ required: true, message: '请填写收货人' }]} />
        {/* <FormItem label={'手机号'} name={'mobile'} rules={[{ type: 'phone', required: true, message: '请填写收货人手机号' }]}>
          <TransferChange>
            {(onChange, value) => {
              <Space size={10}>
                <ReInput onChange={onChange} value={value} placeholder={'请填写收货人手机号'} />
                <Button type={'primary'} size={'action'}>一键获取</Button>
              </Space>
            }}
          </TransferChange>
        </FormItem> */}
        {/* <FormItem label={'省市区'} name={'address'} after={<Icon name={'kq-right'} color={'#666'} />}>
          <TransferChange mode={'city'}>
            <Picker cols={3} data={addressOptions}>请选择</Picker>
          </TransferChange>
        </FormItem> */}
        <FormItem
          label={'选择地址'}
          name={'addr'}
          rules={[{ required: true, message: '请选择收货地址' }]}
          readOnly={true}
          after={<Icon name={'kq-right'} color={'#666'} />}
        >
          <ReTextarea placeholder={'请选择收货地址'} />
        </FormItem>
        <FormItem label={'门牌号'} name={'streetNumber'} rules={[{ required: true, message: '请填写详细地址，如：1栋101' }]} />
        <Button type={'primary'}>确定</Button>
      </Form>
    </View>
  )
}

export default AddrAdd;

**Comment by comlejade** [comment]
![image](https://user-images.githubusercontent.com/15702577/148738811-2fdb4577-8524-4f1b-b934-deb3bb7cbf29.png)

两都注掉就正常了

**Comment by mushan0x0** [comment]
![image](https://user-images.githubusercontent.com/29084441/148739314-7bbd4e74-89b9-48cf-8dd5-4cd1816ca922.png)
我的没问题也
remax@^2.15.11
@kqinfo/ui@^1.8.75

**Comment by comlejade** [comment]
![image](https://user-images.githubusercontent.com/15702577/148739547-13c4fe0a-e2d2-47bf-ae53-cee44bc56cb7.png)

**Comment by mushan0x0** [comment]
删除dist，重新dev一下试试

**Comment by comlejade** [comment]
我把 node_modules 都一起删了重装，也没用

**Comment by mushan0x0** [comment]
这。。dist也删过吗，还是不行的话你加看加钉钉群，我帮你看一下

**Comment by comlejade** [comment]
> 这。。dist也删过吗，还是不行的话你加看加钉钉群，我帮你看一下

下班了，等我晚点回家在看看，也可能是跟我项目里的其他东西有冲突，就是那个vant 的表单用的有问题，我想试试这个，没想到，mummm。。。

**Comment by mushan0x0** [comment]
复现了，取消注释手机号这个formItem才会出现。。。我看一下什么原因

**Comment by mushan0x0** [comment]
![image](https://user-images.githubusercontent.com/29084441/148741455-22e4735a-4c6f-4562-bbdb-3d7a7161a5d1.png)
这里少了个return，导致的

**Comment by comlejade** [comment]
这。。。有点尴尬😅

**Comment by mushan0x0** [comment]
解决了就行，这个先关了
