### ISSUE TITLE
form.setFieldsValue 赋值无效

### ISSUE THREAD

**Issue by comlejade** [cqkqinfo/ui#5]
![image](https://user-images.githubusercontent.com/15702577/148890228-ca9544da-6112-4c4b-84e7-3c167b817c8e.png)

第一次赋值有效，编辑输入框之后，再点按钮就无效了
我看网上有说 用 setTimeout 延迟设置，还是没用
看这个repo
https://github.com/comlejade/kq-test.git

**Comment by mushan0x0** [comment]
收到，我看看

**Comment by comlejade** [comment]
> 收到，我看看

怎没样，找到问题了吗？

**Comment by mushan0x0** [comment]
6149ce98eeb78c25c82c7fe3573df2a9a43d44cd 修复了，更新一下再试试吧
