### ISSUE TITLE
formItem type="number" 的时候这个取值还有验证好像有问题呀

### ISSUE THREAD

**Issue by comlejade** [cqkqinfo/ui#8]
![image](https://user-images.githubusercontent.com/15702577/149055204-bc41b004-7ce9-4f53-98b8-2a6e475a2bd3.png)
![image](https://user-images.githubusercontent.com/15702577/149055264-cf699478-9245-440f-b761-5e67c7f2b508.png)

看这个
https://github.com/comlejade/kq-test.git

**Comment by comlejade** [comment]
type=float 好像也是，这里小数处理好像有问题

**Comment by mushan0x0** [comment]
input输入的值都是字符串，只有InputNumber的值才是number的，想校验input输入的数字字符串可以用正则来判断，或者用formItem的normalize属性把字符串转成number

**Comment by mushan0x0** [comment]
required设为true报错默认消息都是该字段是必填的，可以自己设置message

**Comment by comlejade** [comment]
那我要想弹出不同的键盘，idcard, number, digit 这些都只能用 ReInput 咯

**Comment by mushan0x0** [comment]
可以用remax里的input
```tsx
<FormItem trigger='onInput' normalize={e => e.detail.value}><Input/></FormItem>
```
但是没必要，本质ReInput和Input是一样的，只不过填了一些remax和微信input的坑，就连reInput的placeholder都是自己实现的
